# Your Website Title
title: Duarte Henriques

# Your Website URL
url: 'http://duarteabh.github.io'

# Leave it default
baseurl: '' 

# Index page and Profile Information
name: Duarte Henriques
tagline: 2D Animator
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: 2D Animator
description_tiny: 'duarteabh@gmail.com'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm